---
# Title: unifi-backup-config
#
# Author: Bitfinity-NL / L. Rutten
# File: tasks/unifi-backup-config.yml
#
# Description:
#   Backup the Unifi network autobackup files
#   to the Ansible server.

- name: "Ensure backup directory is present at the Ansible server "
  local_action:
    module: file
    path: "{{ unifi_dest }}"
    owner: "{{ def_ansible_user }}"
    group: "{{ def_ansible_group }}"
    state: directory
  become: yes
  become_user: "{{ def_ansible_user }}"
  become_method: sudo
        
- name: "Fetch autobackup config from the Unifi Network Controller"
  local_action: command "rsync ansible@{{ unifi_host }}:{{ unifi_path }} {{ unifi_dest }} -vrL"
  become: yes
  become_user: "{{ def_ansible_user }}"
  become_method: sudo
