---
# Title: unifi-backup-config
#
# Author: Bitfinity-NL / L. Rutten
# File: tasks/unifi-backup-config.yml
#
# Description:
#   Backup the Unifi network autobackup files
#   to the Ansible server.
#

- hosts: localhost
  become: yes

  tasks:
    - name: "Fetch autobackup config from the Unifi Network Controller"
      command: "rsync ansible@{{ unifi_host }}:{{ unifi_path }} {{ unifi_dest }} -vrL"
      become: yes
